from enum import Enum

class Category(str, Enum):
    STORAGE_SECURITY = "STORAGE_SECURITY"
    NETWORK_SECURITY = "NETWORK_SECURITY"
    IAM_SECURITY = "IAM_SECURITY"
    DATABASE_SECURITY = "DATABASE_SECURITY"
