"""
autofix_pr_service.py — Autofix PR Body Builder

Generates structured, explainable PR bodies for every auto-fix PR that SentraAI creates.
The PR body is the PRIMARY TRUST SIGNAL for developers reviewing the remediation.

Design goals:
- Maximum clarity — developer must understand WHY this PR was created
- Explicit confidence communication — never oversell
- Rollback guidance — easy to undo if something goes wrong
- Suppression path — shows how to acknowledge the issue without merging the fix
- PR fingerprint — embedded for deduplication and telemetry sync
- Commit signing — SentraAI automation identity for audit trails
"""

import hashlib
from typing import Optional
from shared.schemas.finding_schema import Finding, FixSafetyTier
from remediation_engine.autofix_policy import AutofixPolicy
from shared.constants.comment_signature import COMMENT_SIGNATURE


# Automation identity — embedded in commit messages and PR bodies for audit trails
SENTRAAI_IDENTITY = "SentraAI Autofix Engine"
SENTRAAI_SIGNOFF = "Signed-off-by: SentraAI Autofix Engine <autofix@sentra-ai.internal>"


def compute_pr_fingerprint(rule_id: str, file_path: str, remediation_diff: Optional[str]) -> str:
    """
    Computes a SHA256 fingerprint for a specific autofix PR.
    Used for deduplication, telemetry sync, and stale PR detection.

    The fingerprint is stable for the same rule+file+diff combination.
    If the source file changes, the diff changes, and the fingerprint changes,
    enabling drift detection.
    """
    raw = f"{rule_id}:{file_path}:{remediation_diff or ''}"
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()[:16]  # First 16 chars for readability


def compute_source_content_hash(content: str) -> str:
    """SHA256 of the original vulnerable content. Used for drift detection."""
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


def build_autofix_pr_title(finding: Finding) -> str:
    """Generates a clear, standardized PR title."""
    rule_slug = finding.rule_id.lower().replace("_", "-")
    resource = f"{finding.resource_type}.{finding.resource_name}" if finding.resource_type else finding.file_path
    return f"[SentraAI] Security Fix: {finding.rule_id} on {resource}"


def build_autofix_commit_message(finding: Finding, scan_id: str) -> str:
    """
    Generates the commit message for the autofix change.
    Includes commit signing for automation identity and audit provenance.
    """
    resource = f"{finding.resource_type}.{finding.resource_name}" if finding.resource_type else finding.file_path
    return (
        f"fix({finding.rule_id.lower()}): remediate {finding.title} on {resource}\n\n"
        f"Auto-generated by SentraAI Security Scanner.\n"
        f"Rule: {finding.rule_id} (v{finding.rule_version})\n"
        f"File: {finding.file_path}\n"
        f"Scan Trace ID: {scan_id}\n\n"
        f"{SENTRAAI_SIGNOFF}"
    )


def build_autofix_pr_body(
    finding: Finding,
    policy: AutofixPolicy,
    scan_id: str,
    original_pr_number: int,
    pr_fingerprint: str,
    validation_checks: Optional[dict] = None
) -> str:
    """
    Builds the complete PR body for an auto-fix pull request.

    Sections:
    1. Header — why this PR was generated, original PR link
    2. Automated Validation Checks — status of syntax, CLI validate, and boundary checks
    3. Fix Preview — what changed, confidence, safety tier
    4. Conditional review note — for REVIEW_REQUIRED rules (e.g. SG CIDR)
    5. Suppression Guidance — how to close this PR and suppress instead
    6. Rollback Guidance — how to revert if the fix causes issues
    7. Footer — trace ID, rule version, fingerprint, automation identity
    """
    lines = []

    # ── Header ──────────────────────────────────────────────────────────────
    severity_val = finding.severity.value
    resource = f"`{finding.resource_type}.{finding.resource_name}`" if finding.resource_type else f"`{finding.file_path}`"
    tier_badge = _tier_badge(finding.fix_safety_tier)

    lines += [
        COMMENT_SIGNATURE,
        f"## 🛡️ SentraAI Auto-Fix: `{finding.rule_id}` (v{finding.rule_version})",
        "",
        f"> This pull request was automatically generated by **SentraAI Security Scanner** "
        f"during a security review of PR #{original_pr_number}.",
        "",
        f"| Field | Value |",
        f"|---|---|",
        f"| **Rule** | `{finding.rule_id}` |",
        f"| **Severity** | {severity_val} |",
        f"| **Resource** | {resource} |",
        f"| **File** | `{finding.file_path}` |",
        f"| **Fix Safety Tier** | {tier_badge} |",
        f"| **Confidence** | `{finding.fix_confidence:.0%}` |",
        f"| **Requires Human Review** | {'✅ Yes — see note below' if finding.requires_human_review else '❌ No (SAFE tier fix)'} |",
        "",
    ]

    # ── Automated Validation Checks (Trust signals) ─────────────────────────
    if validation_checks:
        lines += [
            "### 🔒 Automated Validation Checks Passed",
            "",
            "| Validation Layer | Status | Details |",
            "|---|---|---|",
        ]
        
        # Syntax check
        syntax_status = "✅ **PASSED**" if validation_checks.get("syntax") else "❌ **FAILED**"
        lines.append(f"| **HCL Syntax Validation** | {syntax_status} | In-memory syntax parsed successfully |")

        # CLI Validate
        cli_val = validation_checks.get("cli")
        if cli_val == "PASSED":
            cli_status = "✅ **PASSED**"
            cli_details = "`terraform validate` executed successfully"
        elif cli_val == "SKIPPED":
            cli_status = "⚠️ **SKIPPED**"
            cli_details = "CLI not present in PATH (fallback bypassed)"
        else:
            cli_status = "❌ **FAILED**"
            cli_details = f"Validation warning: {cli_val}"
        lines.append(f"| **Terraform CLI Validation** | {cli_status} | {cli_details} |")

        # Boundary check
        boundary_status = "✅ **PASSED**" if validation_checks.get("boundary") else "❌ **FAILED**"
        boundary_details = f"Changes restricted to target `{finding.resource_type}.{finding.resource_name}` block boundaries"
        lines.append(f"| **Resource Boundary Safety** | {boundary_status} | {boundary_details} |")
        lines.append("")


    # ── Why This PR Was Generated ────────────────────────────────────────────
    lines += ["### Why This PR Was Generated", ""]
    if finding.explanation:
        lines += [
            f"**Risk**: {finding.explanation.get('risk_summary', finding.description)}",
            "",
            f"**Impact**: {finding.explanation.get('why_it_matters', '')}",
            "",
            f"**Recommended Action**: {finding.explanation.get('recommended_action', finding.recommended_fix)}",
            "",
        ]
    else:
        lines += [finding.description, "", f"**Fix**: {finding.recommended_fix}", ""]

    # ── Fix Preview (Improvement #5) ─────────────────────────────────────────
    lines += ["### Fix Applied", ""]
    if finding.remediation_diff:
        lines += [
            "<details>",
            "<summary>📋 View Diff — Click to expand</summary>",
            "",
            "```diff",
            finding.remediation_diff.strip(),
            "```",
            "",
            "</details>",
            "",
        ]

    # ── Conditional Review Note (for REVIEW_REQUIRED) ────────────────────────
    if policy.pr_review_note:
        lines += [
            "> [!WARNING]",
            f"> {policy.pr_review_note}",
            "",
        ]

    # ── Suppression Guidance ─────────────────────────────────────────────────
    lines += [
        "### If This Fix Is Not Appropriate",
        "",
        "If this resource must remain in its current configuration (e.g., a public CDN bucket), "
        "**close this PR** and suppress the finding with an expiring annotation:",
        "",
        "```hcl",
        f"# sentra-ignore: {finding.rule_id} expires=YYYY-MM-DD -- <your reason here>",
        f'resource "{finding.resource_type}" "{finding.resource_name}" {{',
        "  # ... your configuration",
        "}",
        "```",
        "",
        "> [!NOTE]",
        "> Suppressions without a reason and expiration date will generate a warning in the next scan.",
        "",
    ]

    # ── Rollback Guidance (Improvement #6) ───────────────────────────────────
    lines += [
        "### Rollback",
        "",
        "If this remediation causes unexpected issues after merging:",
        "",
        "1. **Revert this PR** using GitHub's revert button",
        f"2. Restore the previous configuration in `{finding.file_path}`",
        f"3. Add a `sentra-ignore` annotation with a documented reason and expiration date",
        f"4. Open a ticket to schedule a proper remediation with your security team",
        "",
        "> [!CAUTION]",
        "> **Never auto-merge security fixes without review.** "
        "This PR was generated automatically. A human engineer should verify the diff "
        "is correct for your specific infrastructure context before merging.",
        "",
    ]

    # ── Footer (Trace + Fingerprint + Identity) ───────────────────────────────
    lines += [
        "---",
        "",
        "| Metadata | Value |",
        "|---|---|",
        f"| **Trace ID** | `{scan_id}` |",
        f"| **Rule Version** | `{finding.rule_version}` |",
        f"| **PR Fingerprint** | `{pr_fingerprint}` |",
        f"| **Generated By** | {SENTRAAI_IDENTITY} |",
        f"| **Original PR** | #{original_pr_number} |",
        "",
        f"<!-- SentraAI-Fingerprint: {pr_fingerprint} -->",
        f"<!-- SentraAI-RuleID: {finding.rule_id} -->",
        f"<!-- SentraAI-ScanID: {scan_id} -->",
    ]

    return "\n".join(lines)


def _tier_badge(tier: str) -> str:
    """Returns a human-readable badge for the Fix Safety Tier."""
    badges = {
        FixSafetyTier.SAFE: "🟢 **SAFE** — Deterministic, minimal change",
        FixSafetyTier.REVIEW_REQUIRED: "🟡 **REVIEW REQUIRED** — Correct logic, context-dependent values",
        FixSafetyTier.EXPERIMENTAL: "🔴 **EXPERIMENTAL** — Heuristic fix, validate carefully",
        FixSafetyTier.NONE: "⚫ **NONE** — Manual remediation only",
    }
    return badges.get(tier, f"`{tier}`")
